/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package P2Oyun;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.Component;
import java.awt.FlowLayout;
import java.io.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class NewJFrame extends JFrame {
    
    String BASE_DIR = "C:\\P2Oyun";
    String TXT_DIR = BASE_DIR + "\\TXTDosyalar";
    String IMG_DIR = BASE_DIR + "\\Resimler";
    
    String SIFRE_DOSYASI = TXT_DIR + "\\sifre.txt";
    String LOG_DOSYASI = TXT_DIR + "\\log.txt";
    String OYUNLAR_DOSYASI = TXT_DIR + "\\oyunlar.txt";
    String KELIMELER_DOSYASI = TXT_DIR + "\\kelimeler.txt";
    
    int hata = 0;
    int sn = 0;
    Timer timer;
    String kelime = "";

    public NewJFrame() {
        initComponents(); 
        this.setLocationRelativeTo(null); 
        dosyaKontrol();
        
        if (!sifreKontrol()) {
            System.exit(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        lblSure = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        kelimePaneli = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtHarf = new javax.swing.JTextField();
        btnHarfTahmin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtKelime = new javax.swing.JTextField();
        btnKelimeTahmin = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSkorlar = new javax.swing.JTable();
        btnSkorTemizle = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLoglar = new javax.swing.JTable();
        btnLogTemizle = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.addChangeListener(this::jTabbedPane2StateChanged);

        lblSure.setText("Süre:  0 Saniye");

        javax.swing.GroupLayout kelimePaneliLayout = new javax.swing.GroupLayout(kelimePaneli);
        kelimePaneli.setLayout(kelimePaneliLayout);
        kelimePaneliLayout.setHorizontalGroup(
            kelimePaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        kelimePaneliLayout.setVerticalGroup(
            kelimePaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(kelimePaneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kelimePaneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setText("Harf:");

        btnHarfTahmin.setText("Harf Tahmin");
        btnHarfTahmin.addActionListener(this::btnHarfTahminActionPerformed);

        jLabel3.setText("Kelime:");

        txtKelime.addActionListener(this::txtKelimeActionPerformed);

        btnKelimeTahmin.setText("Kelime Tahmin");
        btnKelimeTahmin.addActionListener(this::btnKelimeTahminActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(lblSure))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHarf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(btnHarfTahmin))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKelime)))
                        .addGap(28, 28, 28)
                        .addComponent(btnKelimeTahmin)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblSure)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHarf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHarfTahmin))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKelime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKelimeTahmin))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Oyun Oyna", jPanel3);

        tblSkorlar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tarih", "Süre", "Sonuç"
            }
        ));
        jScrollPane1.setViewportView(tblSkorlar);

        btnSkorTemizle.setText("Temizle");
        btnSkorTemizle.addActionListener(this::btnSkorTemizleActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSkorTemizle)
                .addGap(218, 218, 218))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSkorTemizle)
                .addGap(39, 39, 39))
        );

        jTabbedPane2.addTab("Eski Skorlar", jPanel4);

        tblLoglar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Log Kayıtları"
            }
        ));
        jScrollPane2.setViewportView(tblLoglar);

        btnLogTemizle.setText("Temizle");
        btnLogTemizle.addActionListener(this::btnLogTemizleActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(btnLogTemizle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogTemizle)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Log Kayıtları", jPanel5);

        jMenu1.setText("Seçenekler");

        jMenuItem1.setText("Oyuna Başla / Yeniden Oyna");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKelimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKelimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelimeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        basla();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnHarfTahminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarfTahminActionPerformed
        // TODO add your handling code here:
        String t = txtHarf.getText();
        if (t.length() > 0) {
            harfDene(t.substring(0, 1));
            txtHarf.setText("");
            txtHarf.requestFocus();
        }
    }//GEN-LAST:event_btnHarfTahminActionPerformed

    private void btnKelimeTahminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelimeTahminActionPerformed
        // TODO add your handling code here:
       String t = txtKelime.getText().trim();
        
        if (t.length() == 1) {
            JOptionPane.showMessageDialog(this, "Kelime tahmini bölümüne tek harf giremezsiniz. Lütfen tam kelimeyi yazın!", "Uyarı", JOptionPane.WARNING_MESSAGE);
            txtKelime.setText("");
            txtKelime.requestFocus();
        } 
        else if (t.length() > 1) {
            harfDene(t); 
            txtKelime.setText("");
        }
    
    }//GEN-LAST:event_btnKelimeTahminActionPerformed

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        // TODO add your handling code here:                                        
        tablolariDoldur();
    
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void btnSkorTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkorTemizleActionPerformed
        // TODO add your handling code here:
        String gSifre = JOptionPane.showInputDialog(this, "Skorları temizlemek için şifrenizi girin:");
        if (gSifre == null) return;
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(SIFRE_DOSYASI));
            String asil = br.readLine();
            br.close();
            
            if (gSifre.equals(asil)) {
                new FileWriter(OYUNLAR_DOSYASI, false).close(); 
                tablolariDoldur();
                JOptionPane.showMessageDialog(this, "Skorlar temizlendi.");
                logtut("Skor geçmişi temizlendi.");
            } else {
                JOptionPane.showMessageDialog(this, "Hatalı şifre!", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_btnSkorTemizleActionPerformed

    private void btnLogTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogTemizleActionPerformed
        // TODO add your handling code here:
        String gSifre = JOptionPane.showInputDialog(this, "Logları temizlemek için şifrenizi girin:");
        if (gSifre == null) return;
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(SIFRE_DOSYASI));
            String asil = br.readLine();
            br.close();
            
            if (gSifre.equals(asil)) {
                new FileWriter(LOG_DOSYASI, false).close();
                tablolariDoldur(); 
                JOptionPane.showMessageDialog(this, "Loglar temizlendi.");
                logtut("Sistem: Log kayıtları temizlendi."); 
            } else {
                JOptionPane.showMessageDialog(this, "Hatalı şifre!", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_btnLogTemizleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }
        //</editor-fold>

        /* Create and display the form */
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHarfTahmin;
    private javax.swing.JButton btnKelimeTahmin;
    private javax.swing.JButton btnLogTemizle;
    private javax.swing.JButton btnSkorTemizle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel kelimePaneli;
    private javax.swing.JLabel lblSure;
    private javax.swing.JTable tblLoglar;
    private javax.swing.JTable tblSkorlar;
    private javax.swing.JTextField txtHarf;
    private javax.swing.JTextField txtKelime;
    // End of variables declaration//GEN-END:variables
private void dosyaKontrol() {
        File txtKlasoru = new File(TXT_DIR);
        File resimKlasoru = new File(IMG_DIR);
        
        if (!txtKlasoru.exists()) {
            txtKlasoru.mkdirs(); 
        }
        if (!resimKlasoru.exists()) {
            resimKlasoru.mkdirs();
        }
    }
private boolean sifreKontrol() {
       File sifDosya = new File(SIFRE_DOSYASI);
       String asilSifre = "";

        try {
            if (!sifDosya.exists() || sifDosya.length() == 0) {
                asilSifre = JOptionPane.showInputDialog(this, "İlk defa giriyorsunuz şifre oluşturun: ", "Şifre Belirleme", JOptionPane.INFORMATION_MESSAGE);
                if (asilSifre == null || asilSifre.trim().isEmpty()) {
                    return false;
                }
                BufferedWriter bw = new BufferedWriter(new FileWriter(sifDosya));
                bw.write(asilSifre);
                bw.close();
                
                logtut("Yeni şifren belirlendi.");
            } else {
                BufferedReader br = new BufferedReader(new FileReader(sifDosya));
                asilSifre = br.readLine();
                br.close();
            }
            for (int i = 0; i < 3; i++) {
                String gSifre = JOptionPane.showInputDialog(this, "Şifrenizi girin:  (Kalan Hak: " + (3 - i) + "):", "Giriş", JOptionPane.QUESTION_MESSAGE);
                
                if (gSifre == null) {
                    logtut("Kullanıcı girişi iptal etti.");
                    return false; 
                }
                
                if (gSifre.equals(asilSifre)) {
                    logtut("Başarılı giriş yapıldı.");
                    JOptionPane.showMessageDialog(this, "Giriş Başarılı! Hoş Geldiniz.");
                    return true;
                } else {
                    logtut("Hatalı şifre denemesi.");
                    JOptionPane.showMessageDialog(this, "Şifren hatalı!", "Hata", JOptionPane.ERROR_MESSAGE);
                }
            }
            logtut("3 defa hatalı giriş yapıldı. Program sonlanıyor.");
            JOptionPane.showMessageDialog(this, "3 kez hatalı girdiniz.Sistem kapatılıyor.", "Hata", JOptionPane.ERROR_MESSAGE);
            return false;
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Dosya okuma hatası!", "Hata", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private void logtut(String islem) {
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(LOG_DOSYASI, true));
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
            LocalDateTime simdi = LocalDateTime.now();
            
            bw.write("[" + dtf.format(simdi) + "] - " + islem + "\n");
            bw.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

   private String kelimeSec() {
        List<String> list = new ArrayList<>();
        try {
            BufferedReader br = new BufferedReader(new FileReader(KELIMELER_DOSYASI));
            String satir;
        
            while ((satir = br.readLine()) != null) {
                if (satir.trim().length() >= 6) { 
                    list.add(satir.trim().toUpperCase());
                }
            }
            br.close();
            
            Random r = new Random();  
            return list.get(r.nextInt(list.size()));
            
        } catch (Exception e) {
            return "PROGRAMLAMA";
        }
    }

    private void basla() {
        hata = 0; 
        sn = 0; 
        lblSure.setText("Süre: 0 Saniye"); 
        kelime = kelimeSec();
        
        kelimePaneli.removeAll();
        kelimePaneli.setLayout(new FlowLayout());
        
        for (int i = 0; i < kelime.length(); i++) {
            JLabel yildiz = new JLabel("*");
            kelimePaneli.add(yildiz);
        }
       
        kelimePaneli.revalidate();
        kelimePaneli.repaint();
        
        resimDegis(1);
        
        if (timer != null) {
            timer.stop();
        }
        timer = new Timer(1000, e -> {
            sn++;
            lblSure.setText("Süre: " + sn + " Saniye");
        });
        timer.start();
        
        txtHarf.setEnabled(true);
        txtKelime.setEnabled(true);
        btnHarfTahmin.setEnabled(true);
        btnKelimeTahmin.setEnabled(true);
        txtHarf.setText("");
        txtKelime.setText("");
        
        logtut("Yeni oyun başlatıldı.");
    }

    private void resimDegis(int no) {
        String resYol = IMG_DIR + "\\" + no + ".jpg";
        File f = new File(resYol);
        
        if(f.exists()){
            jLabel1.setIcon(new ImageIcon(resYol));
            jLabel1.setText("");
        } 
    }
   private void harfDene(String t) {
        if (t == null || t.trim().isEmpty()) return;
        
        t = t.toUpperCase();
        boolean varmi = false;
        
        if (t.length() == 1) {
            for (int i = 0; i < kelime.length(); i++) {
                if (String.valueOf(kelime.charAt(i)).equals(t)) {
                    JLabel lbl = (JLabel) kelimePaneli.getComponent(i);
                    lbl.setText(t);
                    varmi = true;
                }
            }
        } 
        else {
            if (kelime.equals(t)) {
                for (int i = 0; i < kelime.length(); i++) {
                    JLabel lbl = (JLabel) kelimePaneli.getComponent(i);
                    lbl.setText(String.valueOf(kelime.charAt(i)));
                }
                varmi = true;
            }
        }
        
        if (varmi) {
            bittiMi(); 
        } else {
            hata++;
            resimDegis(hata + 1);
            
            if (hata >= 10) { 
                oyunBitti(false); 
            }
        }
    }
    private void bittiMi() {
        boolean yildiz = false;
        for (Component c : kelimePaneli.getComponents()) {
            JLabel lbl = (JLabel) c;
            if (lbl.getText().equals("*")) {
                yildiz = true; 
                break;
            }
        }
        
        if (!yildiz) {
            oyunBitti(true);
        }
    }

   private void oyunBitti(boolean kazandi) {
        timer.stop(); 
        
        String son = kazandi ? "KAZANDI" : "KAYBETTI";
        String msj = kazandi ? "Tebrikler, oyunu kazandınız!\nSüre: " + sn + " saniye" : "Maalesef asıldınız!\nDoğru Kelime: " + kelime;
        
        JOptionPane.showMessageDialog(this, msj);
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(OYUNLAR_DOSYASI, true));
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
            bw.write(dtf.format(LocalDateTime.now()) + " | " + sn + " saniye | " + son + "\n");
            bw.close();
            logtut("Oyun bitti. Sonuç: " + son);
        } catch (Exception e) {
            e.printStackTrace();
        }
        txtHarf.setEnabled(false);
        txtKelime.setEnabled(false);
        btnHarfTahmin.setEnabled(false);
        btnKelimeTahmin.setEnabled(false);
    }

    private void tablolariDoldur() {
       DefaultTableModel smod = (DefaultTableModel) tblSkorlar.getModel();
       smod.setRowCount(0);
        
        try {
            File oDosya = new File(OYUNLAR_DOSYASI);
            if (oDosya.exists()) {
                BufferedReader br = new BufferedReader(new FileReader(oDosya));
                String sat;
                while ((sat = br.readLine()) != null) {
                    String[] sutunlar = sat.split(" \\| "); 
                    if (sutunlar.length == 3) {
                        smod.addRow(sutunlar);
                    }
                }
                br.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        DefaultTableModel lmod = (DefaultTableModel) tblLoglar.getModel();
        lmod.setRowCount(0);
        
        try {
           File lDosya = new File(LOG_DOSYASI);
            if (lDosya.exists()) {
               BufferedReader br = new BufferedReader(new FileReader(lDosya));
                String sat;
                while ((sat = br.readLine()) != null) {
                    lmod.addRow(new Object[]{sat});
                }
                br.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }
}

    

